### ISSUE TITLE
Appimage breaks on Ubuntu 18.04 dependency issue. 

### ISSUE THREAD

**Issue by RustyRaptor** [yatima1460/Drill#10] opened 2019-05-03 17:58 UTC
**Linux distro**
Kubuntu 18.04

**Runtime type**
Appimage

**Describe the bug**
```
ziad@ziad-Desktop:~/Downloads$ ./Drill-.glibc2.17-x86_64.appimage 
Drill v0.1.1 - Federico Santamorena
https://github.com/yatima1460/drill
Traceback (most recent call last):
  File "drill.py", line 632, in <module>
    Drill()
  File "drill.py", line 519, in __init__
    self.create_window()
  File "drill.py", line 529, in create_window
    self.window = Tk()
  File "/tmp/.mount_Drill-GB0MAR/usr/lib/python3.5/tkinter/__init__.py", line 1880, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    /usr/share/tcltk/tcl8.6 /tmp/.mount_Drill-GB0MAR/usr/lib/tcl8.6 /tmp/.mount_Drill-GB0MAR/lib/tcl8.6 /tmp/.mount_Drill-GB0MAR/usr/library /tmp/.mount_Drill-GB0MAR/library /tmp/.mount_Drill-GB0MAR/tcl8.6.6/library /tmp/tcl8.6.6/library

/usr/share/tcltk/tcl8.6/init.tcl: version conflict for package "Tcl": have 8.6.6, need exactly 8.6.8
version conflict for package "Tcl": have 8.6.6, need exactly 8.6.8
    while executing
"package require -exact Tcl 8.6.8"
    (file "/usr/share/tcltk/tcl8.6/init.tcl" line 19)
    invoked from within
"source /usr/share/tcltk/tcl8.6/init.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list source $tclfile]"


This probably means that Tcl wasn't installed properly.

ziad@ziad-Desktop:~/Downloads$ 
```

**To Reproduce**
Launch appimage from terminal

**Expected behavior**
To not throw a dependency issue

**Screenshots**
No

**Other notes**
I have the latest version of TCL from the repos installed.

**Comment by probonopd** [comment] 2019-05-03 20:27
I can confirm this.

**Comment by yatima1460** [comment] 2019-05-03 23:09
This is Tkinter being a completely broken and outdated library.
This is already fixed with the next GTK release I will commit soon!

**Comment by RustyRaptor** [comment] 2019-05-03 23:10
Oh we already have a GTK release coming? Nice.

**Comment by yatima1460** [comment] 2019-05-03 23:11
![image](https://user-images.githubusercontent.com/7545597/57169841-82d0e500-6e09-11e9-8f71-45753cebf76b.png)

**Comment by yatima1460** [comment] 2019-05-08 23:52
Conversion to D completed, I noticed that the prerequisites of a D compiled binary are nearly the same and very few of an AppImage, so I think now I can fix it soon

![image](https://user-images.githubusercontent.com/7545597/57415606-fe150b00-71fc-11e9-81b8-30ccd3247d87.png)

**Comment by yatima1460** [comment] 2019-05-10 00:58
@probonopd AppImage with D compiled and GTK uploaded

If I understood right only libgcc1 is a requirement

**Comment by yatima1460** [comment] 2019-05-10 02:02
@probonopd  I have confirmation it works on Fedora 30

**Comment by yatima1460** [comment] 2019-05-10 05:53
Duplicate of #11

**Closed by yatima1460** 2019-05-10 05:53 UTC
