### ISSUE TITLE
Drill can't find some files.

### ISSUE THREAD

**Issue by luluco250** [yatima1460/Drill#12] opened 2019-05-11 00:35 UTC
**Linux distro**
Arch Linux

**Runtime type**
AppImage

**Describe the bug**
Drill can't find *some* files, specially those under the user home folder, whereas other programs can. It can't even find it's own app image under ~/Downloads.

**To Reproduce**
1. Open Drill.
2. Type in the name of a file within ~/ (though other folders may be affected as well).
3. It may not find the file you're looking for, even if it exists and can be opened by other programs (including other app images).

**Expected behavior**
Finding the file correctly, as the user has permissions to read it.

**Screenshots**
![image](https://user-images.githubusercontent.com/18670927/57562676-30447b00-736b-11e9-828c-4ccb0aee9f0b.png)

**Other notes**
Probably not a problem with the permissions of the home folder, or others, I have tried giving full read permissions to the home folder and it still didn't work.
Drill ***is*** able to find the file(s) as root (through sudo).

**Comment by RustyRaptor** [comment] 2019-05-12 16:18
Could this be the result of it having a space in the name? I will test it out.

**Comment by RustyRaptor** [comment] 2019-05-12 16:23
Can't reproduce with space in filename.

**Comment by RustyRaptor** [comment] 2019-05-12 16:32
Could you compile Drill in debug mode? 
clone the project using 
```
git clone --recurse-submodules -j8 https://github.com/yatima1460/Drill.git
```
then run
```
dub run -c x64-GTK
```
in it's folder. This will give you feedback about which folders are being crawled when you search something. Just type in the name of the file and see if it ever goes over the folder it's in. 

The fact that it's only indexed 488 files is a bit suspicious unless you really only have that many files in your home.

**Comment by yatima1460** [comment] 2019-05-12 16:35
After having a long discussion with @luluco250 with ended up finding out it's because the thread scanning /home crashes when it encounters a file owned by root with permissions similar to 700 that is inside his home folder

This should be fixed now

**Comment by RustyRaptor** [comment] 2019-05-12 16:52
![Screenshot_20190512_105128](https://user-images.githubusercontent.com/7911442/57585320-f0cd7a00-74a3-11e9-942e-e5371c00ba27.png)
Can not reproduce so looks like it got fixed. Cool.

**Comment by yatima1460** [comment] 2019-05-13 05:14
This got fixed, and I would actually be surprised if this issue reappears

**Closed by yatima1460** 2019-05-13 05:14 UTC
